config/routes.rb
Rails.application.routes.draw do
  root :to => 'stores#index'

  devise_for :users

  resources :stores do
    resources :products do
  
    end
  end
  resources :faqs
  resources :mission

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :store
  validates :product_name, presence: true
end

app/models/store.rb
class Store < ActiveRecord::Base
  validates :title, presence: true
  has_many :products
  has_attached_file :image, :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:attachment/:id/:basename_:style.:extension",
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }
  validates_attachment :image, :presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end


# database_authenticatable – ensures that a user enters a correct password,
# and it encrypts the said password, before saving it.
#
# confirmable – ensures newly registered users confirm their accounts by
# clicking a link on a (Devise sent) mail they receive. This is a defence
# against bots creating fake, but valid, users.
#
# recoverable – for handling forgotten passwords safely.
#
# registerable – allows users to register themselves, and subsequently change
# their login credentials.
#
# rememberable – for transparently logging on a user, based on a cookie. This is
# the functionality associated with the Remember me? checkbox you often see on
# login forms. Since the Devise config file specifies a timeout period, this is
# often of limited use. And is a security risk if the user steps away from their
# browser, with others about.
#
# trackable – stores login information i.e. the user’s IP address, login time,
# last login time, and the total number of logins. These values are generally for
# site admins to look at, when trying to trace unusual activity.
#
# validatable – ensures that the given email/name and passwords conform to a
# particular format.
#
# lockable – limits the number of login attempts allowed before further access
# to a particular account is prohibited. Access restrictions are lifted after a
# time span, or if a (legitimate) user requests that an email be sent that
# contains a link to unblock his/her account.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  def index

  end
end

app/controllers/mission_controller.rb
class MissionController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @store = Store.find(params[:store_id])
    @product = @store.products.new
  end

  def create
    @store = Store.find(params[:store_id])
    @product = @store.products.new(product_params)
    if @product.save
      flash[:notice] = "Product added successfully"
      redirect_to store_path(@product.store)
    else
      render :new
    end
  end

  def destroy
    @store = Store.find(params[:store_id])
    @product = @store.products.find(params[:id])
    if @product.destroy
      flash[:notice] = "This product has been deleted successfully"
    else
      flash[:error] = "This product was NOT deleted successfully"
    end
    redirect_to store_path(@store)
  end

  def edit
    @store = Store.find(params[:store_id])
    @product = @store.products.find(params[:id])
  end

  def update
    @store = Store.find(params[:store_id])
    @product = @store.products.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product was successfully updated"
      redirect_to store_path(@store)
    else
      flash[:error] = "There was an error with your product update"
      render action: :edit
    end
  end

private
  def product_params
    params.require(:product).permit(:product_name)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # before_action :set_stores, only: [:show, :edit, :update, :destroy]

  def index
    @stores = Store.all
  end

  def new
    @store = Store.new
  end

  def show
    @store = Store.find(params[:id])
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      flash[:notice] = "Store created successfully"
      redirect_to stores_path
    else
      render :new
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    if $store.update(store_params)
      redirect_to stores_path
    else
      render :edit
    end
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    redirect_to stores_path
  end

private
  def store_params
    params.require(:store).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h3>What does the OSP do? Do you "bank" seed for later?</h3>

<p>
  The Orchid Seedbank Project is a conservation organization. Although  we do
  store seed, we do not intend on storing it for purposes of  generating large
  numbers of plants at some future point in time; it  is not a "seed bank" in
  the sense that we are routinely cryogenically  freezing seed, or carrying out
  some other hopelessly long-term  storage regimes. Instead, the OSP serves as a
  clearinghouse for  orchid seed; until the OSP was formed in December of 1996,
  there was  no central clearinghouse by which conservationists, researchers,
  commercial and hobbyist growers could go to specifically for orchid seed.
</p>

<h3>How do you get your seed?</h3>

<p>
  We receive our seed from many donors. Sometimes  we receive only one species
  from a given donor, sometimes we get tens  of species in a single shipment.
</p>

<h3>What does the donor get out of it?</h3>

<p>
  Donors receive credit for their donation; right now, this stands at  4:1,
  meaning that if we can make, say, four outgoing packets from the  incoming
  seed, the donor gets one free packet. These credits may be  redeemed at any
  time, and the OSP pays the shipping. We place no  restrictions, other than
  those we place on those that pay for their  seed, upon the seed that the
  donors request.
</p>

<h3>Doesn't this tend to deplete the stocks of  "good" seed?</h3>

<p>
  No. Although demand sometimes surpasses supply, orchids are  remarkably
  prodigious producers of seed, and our donors tend to be  very generous with
  the seed they send. As a result, there is often  more than enough seed to go
  around. Seed is supplied on a first-come,  first-serve basis: our donors and
  those that purchase seed are placed  on equal footing with respect to orders,
  unless they have  specifically requested seed (such as on the "Wanted" list).
  The only exception is that specific conservation agencies receive  slightly
  higher priority; all the same, it is rather rare that seed  is subject to such
  exceptions.
</p>

<h3>How does the OSP serve conservationists and other groups?</h3>

<p>
  The OSP maintains contacts via e-mail with representatives of several  orchid
  conservation groups, as well as recognized experts in  different fields.
  For example, certain rare stanhopea species are  handed off to our stanhopea
  "pros." Cypripediums get  similar treatment, and so on. As such, although we
  strive to conserve  ALL species of orchids, certain species get preferential
  treatment  such that their numbers may be maintained in cultivation.
</p>

<h3>Do you guarantee viability of your seed?</h3>

<p>
  We cannot guarantee viable seed; we do our best on this end to  maintain
  seed under the best possible conditions, but due to the  large volume of
  seed, we cannot test each batch before it leaves. We  have started to examine
  seed for presence or absence of embryos, but  this is NOT a promise of
  germinability or viability. Seed that looks  fine may be too old to germinate,
  or it may be that the seed is still  germinable, but we have not developed the
  technology to sprout it. We  may be going to 2,3,5-TTC testing to determine
  viability before long,  but this step will take a while.
</p>
<p>
  We strongly encourage recipients to relay information about viability  back
  to the OSP; seed that receives more than one or two  unsatisfactory viability
  results will be re-examined, and pulled from  distribution if deemed necessary.
</p>


<h3>How do you ship seed?</h3>

<p>Please see our information under shipping for further information.</p>

<h3>Do you perform research?</h3>

<p>
  The many members of the loose affiliation of OSP growers, donors and
  recipients include researchers from many fields, each of whom have  much to
  offer. We support and work with taxonomists, horticulturists,  chemists,
  biologists, biochemists, and others in the science realm to  expand our
  knowledge of the orchid seed.
</p>

<h3>Cool! Such as?</h3>

<p>
  Improving longevity of seed in storage, use of disinfectants for in  vitro
  propagation, enhancing communication bewteen researchers, and  otherwise
  assisting the Teeming Millions in their pursuits.
</p>

<h3>What types of storage do you use?</h3>

<p>
  We store most of our orchid seed at 4 degrees C, in refrigeration.
  The seed packets are stored with a small container of calcium  chloride/water
  slurry to provide the correct amount of moisture to  provide optimal storage
  conditions for the seeds. We also have a  small number of seeds that are stored
  in liquid nitrogen to determine  if this method of storage is a viable technique
  for conservation and  preservation of species.
</p>

<h3>How do I grow orchids from seed?</h3>

<p>
  Growing orchids from seed is something that can be done either in a
  commercial lab, or in your own home. Although a very few seeds might
  germinate under the correct conditions in the greenhouse, the vast  majority
  of orchids propagated today are done so under sterile  conditions. We
  recommend (not surprisingly) our book  that we have assembled for growers-
  covering everyone from the novice  to the established expert. It tells you
  how to assemble your home  lab, using readily available equipment such as an
  aquarium for a  flasking box, bleach for disinfection, and where to purchase
  the  appropriate media. Sterilization of the media and flasks (Mason jars
  are recommended) is performed with a pressure cooker. Although  designed to
  accomodate the novice, Asymbiotic Technique of Orchid  Seed Germination covers
  HEPA filters, the role of individual  components in orchid germination and
  culture media, making your own  tools, and a complete directory of where to
  purchase almost  everything listed in the manual. It is up to date, having
  been  published in November, 1999.
</p>

<h3>What does the book cost?</h3>

<p>
  About US$45. This is a professional text, consisting of 145 pages of
  referenced scientific material. Consider what your own time is worth.
  Two years in the making, this book covers every conceivable aspect of
  orchid seed germination, from pollination to de-flasking your seedlings.
</p>

<h3>Are you available for lectures and talks?</h3>

<p>
  Only on special occasions. Due to the nature of our  work, we are generally
  busy and, therefore, only very rarely available to give talks. We are happy
  to provide information as to  our activities in research and conservation,
  and would be happy to  provide articles for your society's newsletter.
  Subjects range from orchid book reviews to esoterica on plant  pathogens.
  Please contact ahicks51(at)REMOVEcox.net for more information.
</p>

<h3>Will there be more later?</h3>

<p>
  Yeah; I just piece this stuff together as I go. :-) This is just the
  start of it all.
</p>

app/views/faqs/index.html.erb
<h1>Fequently Asked Questions:</h1>

<h3>What does the OSP do? Do you "bank" seed for later?</h3>

<p>
  The Orchid Seedbank Project is a conservation organization. Although  we do
  store seed, we do not intend on storing it for purposes of  generating large
  numbers of plants at some future point in time; it  is not a "seed bank" in
  the sense that we are routinely cryogenically  freezing seed, or carrying out
  some other hopelessly long-term  storage regimes. Instead, the OSP serves as a
  clearinghouse for  orchid seed; until the OSP was formed in December of 1996,
  there was  no central clearinghouse by which conservationists, researchers,
  commercial and hobbyist growers could go to specifically for orchid seed.
</p>

<h3>How do you get your seed?</h3>

<p>
  We receive our seed from many donors. Sometimes  we receive only one species
  from a given donor, sometimes we get tens  of species in a single shipment.
</p>

<h3>What does the donor get out of it?</h3>

<p>
  Donors receive credit for their donation; right now, this stands at  4:1,
  meaning that if we can make, say, four outgoing packets from the  incoming
  seed, the donor gets one free packet. These credits may be  redeemed at any
  time, and the OSP pays the shipping. We place no  restrictions, other than
  those we place on those that pay for their  seed, upon the seed that the
  donors request.
</p>

<h3>Doesn't this tend to deplete the stocks of  "good" seed?</h3>

<p>
  No. Although demand sometimes surpasses supply, orchids are  remarkably
  prodigious producers of seed, and our donors tend to be  very generous with
  the seed they send. As a result, there is often  more than enough seed to go
  around. Seed is supplied on a first-come,  first-serve basis: our donors and
  those that purchase seed are placed  on equal footing with respect to orders,
  unless they have  specifically requested seed (such as on the "Wanted" list).
  The only exception is that specific conservation agencies receive  slightly
  higher priority; all the same, it is rather rare that seed  is subject to such
  exceptions.
</p>

<h3>How does the OSP serve conservationists and other groups?</h3>

<p>
  The OSP maintains contacts via e-mail with representatives of several  orchid
  conservation groups, as well as recognized experts in  different fields.
  For example, certain rare stanhopea species are  handed off to our stanhopea
  "pros." Cypripediums get  similar treatment, and so on. As such, although we
  strive to conserve  ALL species of orchids, certain species get preferential
  treatment  such that their numbers may be maintained in cultivation.
</p>

<h3>Do you guarantee viability of your seed?</h3>

<p>
  We cannot guarantee viable seed; we do our best on this end to  maintain
  seed under the best possible conditions, but due to the  large volume of
  seed, we cannot test each batch before it leaves. We  have started to examine
  seed for presence or absence of embryos, but  this is NOT a promise of
  germinability or viability. Seed that looks  fine may be too old to germinate,
  or it may be that the seed is still  germinable, but we have not developed the
  technology to sprout it. We  may be going to 2,3,5-TTC testing to determine
  viability before long,  but this step will take a while.
</p>
<p>
  We strongly encourage recipients to relay information about viability  back
  to the OSP; seed that receives more than one or two  unsatisfactory viability
  results will be re-examined, and pulled from  distribution if deemed necessary.
</p>


<h3>How do you ship seed?</h3>

<p>Please see our information under shipping for further information.</p>

<h3>Do you perform research?</h3>

<p>
  The many members of the loose affiliation of OSP growers, donors and
  recipients include researchers from many fields, each of whom have  much to
  offer. We support and work with taxonomists, horticulturists,  chemists,
  biologists, biochemists, and others in the science realm to  expand our
  knowledge of the orchid seed.
</p>

<h3>Cool! Such as?</h3>

<p>
  Improving longevity of seed in storage, use of disinfectants for in  vitro
  propagation, enhancing communication bewteen researchers, and  otherwise
  assisting the Teeming Millions in their pursuits.
</p>

<h3>What types of storage do you use?</h3>

<p>
  We store most of our orchid seed at 4 degrees C, in refrigeration.
  The seed packets are stored with a small container of calcium  chloride/water
  slurry to provide the correct amount of moisture to  provide optimal storage
  conditions for the seeds. We also have a  small number of seeds that are stored
  in liquid nitrogen to determine  if this method of storage is a viable technique
  for conservation and  preservation of species.
</p>

<h3>How do I grow orchids from seed?</h3>

<p>
  Growing orchids from seed is something that can be done either in a
  commercial lab, or in your own home. Although a very few seeds might
  germinate under the correct conditions in the greenhouse, the vast  majority
  of orchids propagated today are done so under sterile  conditions. We
  recommend (not surprisingly) our book  that we have assembled for growers-
  covering everyone from the novice  to the established expert. It tells you
  how to assemble your home  lab, using readily available equipment such as an
  aquarium for a  flasking box, bleach for disinfection, and where to purchase
  the  appropriate media. Sterilization of the media and flasks (Mason jars
  are recommended) is performed with a pressure cooker. Although  designed to
  accomodate the novice, Asymbiotic Technique of Orchid  Seed Germination covers
  HEPA filters, the role of individual  components in orchid germination and
  culture media, making your own  tools, and a complete directory of where to
  purchase almost  everything listed in the manual. It is up to date, having
  been  published in November, 1999.
</p>

<h3>What does the book cost?</h3>

<p>
  About US$45. This is a professional text, consisting of 145 pages of
  referenced scientific material. Consider what your own time is worth.
  Two years in the making, this book covers every conceivable aspect of
  orchid seed germination, from pollination to de-flasking your seedlings.
</p>

<h3>Are you available for lectures and talks?</h3>

<p>
  Only on special occasions. Due to the nature of our  work, we are generally
  busy and, therefore, only very rarely available to give talks. We are happy
  to provide information as to  our activities in research and conservation,
  and would be happy to  provide articles for your society's newsletter.
  Subjects range from orchid book reviews to esoterica on plant  pathogens.
  Please contact ahicks51(at)REMOVEcox.net for more information.
</p>

<h3>Will there be more later?</h3>

<p>
  Yeah; I just piece this stuff together as I go. :-) This is just the
  start of it all.
</p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OSP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/navbar" %>
  <div class="container">
    <div class="row row-centered">
      <div class="col-md-8 col-centered">
        <% flash[:alert] %>
        <% flash[:notice] %>
        <%= yield %>

      </div>
    </div>
  </div>
  <footer>

  </footer>
</body>
</html>

app/views/mission/index.html.erb
<h1>Our Mission:</h1>
<p>
  The family of orchids is probably the largest family of flowering plants,
  with somewhere between 20,000 and 22,000 individual species. Counting
  varieties and subspecies and other taxonomical hair-splitting, the estimates
  have ranged as high as 30,000.
</p>

<p>
  Unfortunately, due to the changes occurring to our planet because of
  anthropogenic (human) and natural causes, many species of living creatures are
  threatened with extinction. Due to the combination of 6 billion hungry human
  mouths to feed, and devastating consumption on the part of industrial nations,
  the natural habitat for many species has been dramatically reduced. As much as
  96% of the primary forest of Madagascar, for example, has been destroyed.
</p>

<p>
  Of course, it would be wonderful to conserve and preserve everything forever
  and ever. From a paleontological standpoint, over 99.9% of all species that
  have ever existed are now extinct. Why worry about a few more?
</p>

<p>
  The rate of species extinction is currently so high that it exceeds that
  experienced during the mass extinctions of geological history, including that
  of the K/T which is when the dinosaurs were wiped out. Despite the research
  that has been poured into extinction, we know relatively little. Worse, we
  know virtually nothing about the house of cards which is our biosphere. How
  much damage, precisely, can an environment suffer until the top consumers
  expire?
</p>

<p>
  Humans are, of course, the "top consumers." We are busy destroying our oceans,
  salinifying the land, depleting the nutrients of our agricultural areas, and
  polluting our air. Perhaps we are responsible for climate change and the ozone
  hole. All of these do not bode well for those of us that are at the top of the
  food chain.
</p>

<p>
  There is only so much that one organization or group can do. We've chosen
  orchids, and given the width and breadth of the Orchidaceae, this will be
  plenty enough. We fully recognize that the work we do here is of limited
  scope: if we cut down the rainforest, after all, what good are the orchids
  we 'rescue' if there is nowhere to return them? I will happily admit that
  conservation of species out of their natural environment ("ex situ"
  conservation) is far inferior to the preservation of an entire ecosystem.
  At the same time, it's either this or nothing. All we're trying to do is keep
  our kids (no, we don't have any, but what the hey) from being able to point
  to a picture of an extinct species and ask why there aren't any left.
</p>

<p>Just a little responsibility in the great scheme of things.</p>

<p>
  So all we try to do is foster conservation through propagation of orchids.
  We send out information, products, new research data, and, well... lots of
  stuff. Our recipients don't just get seeds- they get our best advice, information,
  and (in developing countries and research labs) some of the compounds and
  chemicals needed to keep going.
</p>

<p>
  We'd like to work with more growers in developing countries to help get them
  going with more information (such as copies of our book), and spreading
  information about media that can be formulated inexpensively, using fertilizer
  and other readily available chemicals. We also do some research here to
  develop new formulae.
</p>

<p>
  But we need help. We need more donors, more recipients, and (most of all) a
  new facility. Corporate sponsors, in a word, would be great. Drop us a line
  if you're willing to help. We're looking for a leg up, not a handout.
</p>

<p>
  Thanks. And tread softly. Once we wreck this island, it's not like we can
  leave it for another.
</p>

app/views/products/_form.html.erb
<div class="admin_controls">
  <h3>Admin controls:</h3>
  <% render "layouts/errors", :object => @store %>

  <%= form_for [@store, @product] do |f| %>
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Edit product:</h1>

<%= render 'form' %>

app/views/products/new.html.erb
<h1>Create new product in <%= @store.title %></h1>
<%= render 'form' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Orchid<br> Seedbank Project</a>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Store <span class="sr-only">(current)</span></a></li>
          <li><a href="/faqs">FAQ</a></li>
          <li><a href="/mission">Mission</a></li>
          <%= render 'devise/menu/login_items' %>
        </ul>
        <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      </div>
    </div>
  </div>
</nav>

app/views/stores/_form.html.erb
<div class="admin_controls">
  <h3>Admin controls:</h3>
  <% render "layouts/errors", :object => @store %>

  <%= form_for @store, :url => stores_path, :html => { :multipart => true } do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/stores/edit.html.erb
<h1>Edit <%= @store.title %> Store:</h1>

<%= render 'form' %>

app/views/stores/index.html.erb
<h1>OSP - selling orchid seeds and related products since 1996!</h1>

<ul>
  <% @stores.each do |store| %>
    <li><%= image_tag store.image.url(:thumb) %></li>
    <li><%= link_to store.title, store_path(store) %></li>
  <% end %>
</ul>

<div class="admin_controls">
  <h3>Admin controls:</h3>
  <p><%= link_to "Create store", new_store_path %></p>
</div>

app/views/stores/new.html.erb
<h1>New Store:</h1>
<%= render 'form' %>

app/views/stores/show.html.erb
<h1><%= @store.title %></h1>
<%= image_tag @store.image.url(:thumb) %>

<% if @store.products.any? %>
  <% @store.products.each do |product| %>
  <ul>
    <li>
      <%= product.product_name %>
      <div class="admin_controls">
        <%= link_to "Edit", edit_store_product_path(@store, product) %>
        <%= link_to "Delete", store_product_path(@store, product), data: { confirm: "Are you sure?", method: "delete" } %>
      </div>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>This store has no products yet</p>
<% end %>


<div class="admin_controls">
  <h3>Admin controls:</h3>
  <p><%= link_to "Edit", edit_store_path(@store) %></p>
  <p><%= link_to "Delete", store_path(@store), data: { confirm: "Are you sure?", method: "delete" } %></p>
  <p><%= link_to "Add product", new_store_product_path(@store, @product) %></p>
</div>

<p><%= link_to "Return to home", stores_path %></p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>